### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by pMat-19** [nhrrs/heboric-obsidian#1]
Hey there, I chose your Theme mainly because of your chosen fonts but you seen to have reverted them back to the default ones.
Which were they? Would love to use them, thanks.

**Comment by nhrrs** [comment]
This was changed as the user couldn't override them through Obsidian, but I've updated it now so that the default fonts are as they were before, and they can be overridden via `Settings > Appearance > Font`.

If you update the theme, and remove any font settings in obsidian, it should be back to how it was.

If you're still wondering, the default font for the main text was (and now is again) 'New York', or if you didn't have that installed, 'Georgia'.
